# Generated by Django 4.2.1 on 2023-06-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='detalleEstadisticoDiscapacitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadHombre', models.IntegerField()),
                ('cantidadMujeres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRubro', models.CharField(max_length=30, verbose_name='Nombre Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='sectorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSector', models.CharField(max_length=30, verbose_name='Nombre Sector')),
            ],
        ),
        migrations.CreateModel(
            name='tipoDiscapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDiscapacidad', models.CharField(max_length=30, verbose_name='Nombre Discapacidad')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado')),
            ],
        ),
    ]
