# Generated by Django 4.2.1 on 2023-06-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_categoriaocupacional_rubro_sectoreconomico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaocupacional',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='idRubro',
        ),
        migrations.RemoveField(
            model_name='sectoreconomico',
            name='idSector',
        ),
    ]
