# Generated by Django 4.2.1 on 2023-06-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_delete_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectoreconomico',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado'),
        ),
    ]
