# Generated by Django 4.2.1 on 2023-06-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_sectoreconomico_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ragoEdades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragoEdad', models.CharField(max_length=5, verbose_name='Rango Edad')),
            ],
        ),
    ]
