# Generated by Django 4.2.1 on 2023-06-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_categoriaocupacional_detalle_ragoedades_detalle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragoedades',
            old_name='ragoEdad',
            new_name='rangoEdad',
        ),
    ]
