# Generated by Django 4.2.1 on 2023-06-03 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_ragoedad_ragoedades_rangoedad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ragoEdades',
            new_name='rangoEdades',
        ),
    ]
